# Generated by Django 4.1 on 2022-08-17 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='secondary_categories',
        ),
        migrations.AlterField(
            model_name='product',
            name='primary_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.category'),
        ),
    ]
